<?php

class CookieEngine
{
    private const KNOWN_COOKIE_KEYS = ['NetflixId', 'SecureNetflixId'];

    private const COOKIE_INDICATORS = ['id', 'token', 'cookie', 'session', 'auth', 'sid', 'jwt'];

    public static function detectCookies(array $fields): array
    {
        $cookies = [];

        foreach ($fields as $item) {
            if ($item['type'] === 'cookie') {
                $cookies[$item['key']] = $item['value'];
                continue;
            }

            if (in_array($item['key'], self::KNOWN_COOKIE_KEYS, true)) {
                $cookies[$item['key']] = $item['value'];
                continue;
            }
        }

        return $cookies;
    }

    public static function detectDomainFromData(array $fields): string
    {
        foreach ($fields as $item) {
            if ($item['type'] === 'url' && is_string($item['value'])) {
                $parsed = parse_url($item['value']);
                if (!empty($parsed['host'])) {
                    $host = $parsed['host'];
                    $host = preg_replace('/^www\./', '', $host);
                    return '.' . $host;
                }
            }
        }

        foreach ($fields as $item) {
            if (is_string($item['value']) && preg_match('/https?:\/\/([^\/\s?]+)/', $item['value'], $m)) {
                $host = preg_replace('/^www\./', '', $m[1]);
                return '.' . $host;
            }
        }

        return '.netflix.com';
    }

    public static function generateNetscape(array $cookies, string $domain = '.netflix.com'): ?string
    {
        if (empty($cookies)) {
            return null;
        }

        $domain = self::sanitizeDomain($domain);
        $expiry = time() + (365 * 24 * 60 * 60);

        $lines   = [];
        $lines[] = '# Netscape HTTP Cookie File';
        $lines[] = '# Generated by ClearOrbit Session Intelligence Engine';
        $lines[] = '# https://curl.se/docs/http-cookies.html';
        $lines[] = '';

        foreach ($cookies as $name => $val) {
            $lines[] = implode("\t", [$domain, 'TRUE', '/', 'TRUE', $expiry, $name, $val]);
        }

        return implode("\n", $lines);
    }

    public static function validateCookies(array $cookies): array
    {
        $result = [
            'valid'          => false,
            'has_netflix_id' => isset($cookies['NetflixId']),
            'has_secure_id'  => isset($cookies['SecureNetflixId']),
            'cookie_count'   => count($cookies),
            'issues'         => [],
        ];

        if (!$result['has_netflix_id']) {
            $result['issues'][] = 'NetflixId cookie is missing';
        } else {
            if (empty(trim($cookies['NetflixId']))) {
                $result['issues'][] = 'NetflixId cookie is empty';
            }
            if (strlen($cookies['NetflixId']) < 10) {
                $result['issues'][] = 'NetflixId cookie appears too short';
            }
        }

        if (!$result['has_secure_id']) {
            $result['issues'][] = 'SecureNetflixId cookie is missing';
        }

        $result['valid'] = $result['has_netflix_id'] && empty(array_filter($result['issues'], fn($i) => str_contains($i, 'empty') || str_contains($i, 'too short')));

        return $result;
    }

    public static function sanitizeDomain(string $domain): string
    {
        $domain = preg_replace('/[^a-zA-Z0-9.\-]/', '', $domain);
        if ($domain === '') {
            $domain = '.netflix.com';
        }
        return $domain;
    }

    public static function parseRawCookieString(string $raw): array
    {
        $result = [];
        $pairs = preg_split('/;\s*/', trim($raw));

        foreach ($pairs as $pair) {
            $pair = trim($pair);
            if ($pair === '') continue;
            $eqPos = strpos($pair, '=');
            if ($eqPos === false) continue;

            $key = trim(substr($pair, 0, $eqPos));
            $val = trim(substr($pair, $eqPos + 1));

            if ($key === '') continue;

            $decoded = str_contains($val, '%') ? rawurldecode($val) : $val;

            $result[] = [
                'key'      => $key,
                'rawValue' => $val,
                'value'    => $decoded,
                'type'     => 'cookie',
            ];
        }

        return $result;
    }
}
